# Nome da aplicacao Spring Boot 
spring.application.name=intercards

# Configuracao do banco MySQL
# spring.datasource.url=jdbc:mysql://localhost:3306/intercards
# spring.datasource.username=root
# spring.datasource.password=
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuracao do banco Postgres
# spring.datasource.url=jdbc:postgresql://ep-still-thunder-atjainy6-pooler.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
# spring.datasource.username=neondb_owner
# spring.datasource.password=npg_aLWFkeKvGn26
# spring.datasource.drive-class-name=org.postgresql.Driver
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.drive-class-name=org.postgresql.Driver


# Configuracao do JPA
spring.jpa.hibernate.ddl-auto=create     
# spring.jpa.hibernate.ddl-auto=update     

# Configuracoes de exibicao de SQL no console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=truel